CREATE TABLE IF NOT EXISTS PLAYERS(
    ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    PHONE_NUMBER VARCHAR(255),
    NICKNAME VARCHAR(255) NOT NULL,
    GROUP_NICKNAME VARCHAR(255) NOT NULL,

    CONSTRAINT UNIQUE_NICKNAME UNIQUE (NICKNAME, GROUP_NICKNAME),
)